# Generated by Django 4.0.6 on 2022-07-13 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0003_rename_work_hours_employee_extra_work_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='grade_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Grade_fk', to='employeeapp.grade'),
        ),
    ]
